// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbwggtovxkvsdyqgdqdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZid2dndG92eGt2c2R5cWdkcWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDA1MDYsImV4cCI6MjA1ODY3NjUwNn0.cZEl-MoBmynFNZ58uNGKNJOTxhGrTconZTnyBKFtXjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);