// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mawybgxzetkdjnftunuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hd3liZ3h6ZXRrZGpuZnR1bnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzUwMDQsImV4cCI6MjA2NzU1MTAwNH0.LHWx80WdvRikRYcEdRUV7IdjAagOj005CN9ykUcXMO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});